Repository mia-platform/js-crud-service-client, pull requests merged in 2024-12, with the labels that each got.

#8 chore(docs): Added library documentation
  README.md
Labels: documentation

#10 fix(type): added missing __STATE__ in CrudItem type
  src/types.ts
Labels: bug

#11 feat: switch to CommonJS
  package.json
  scripts/tsconfig.build.json
  src/CrudClient.ts
  src/index.ts
  src/types.ts
  src/utils.ts
  tests/CrudClient.test.ts
  tsconfig.json
  yarn.lock
Labels: breaking, refactor
